name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: yarn install
      
    - name: Run tests
      run: yarn test
      
    - name: Build and deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm run build
        docker build -t my-express-app .
        docker tag my-express-app:latest aws_account_id.dkr.ecr.us-east-1.amazonaws.com/my-express-app:latest
        $(aws ecr get-login --no-include-email)
        docker push aws_account_id.dkr.ecr.us-east-1.amazonaws.com/my-express-app:latest
